#!/bin/bash
# Vercel Deployment - Quick Command Reference
# Copy and paste these commands one at a time

echo "========================================="
echo "VERCEL DEPLOYMENT - COMMAND SEQUENCE"
echo "========================================="
echo ""

echo "STEP 1: Login to Vercel"
echo "------------------------"
echo "vercel login"
echo ""
echo "→ This will open a browser for authentication"
echo "→ Sign in with GitHub (recommended)"
echo ""

echo "STEP 2: Deploy to Vercel"
echo "------------------------"
echo "cd /home/user/booktarr"
echo "vercel --prod"
echo ""
echo "→ Answer prompts:"
echo "  - Set up and deploy? Y"
echo "  - Which scope? (select your account)"
echo "  - Link to existing project? N"
echo "  - Project name? booktarr"
echo "  - Code location? ./apps/web"
echo "  - Override settings? N"
echo ""

echo "STEP 3: Set Up Neon Database"
echo "----------------------------"
echo "1. Go to https://neon.tech"
echo "2. Sign up with GitHub"
echo "3. Create project: booktarr-staging"
echo "4. Copy connection string"
echo ""

echo "STEP 4: Add Environment Variables"
echo "----------------------------------"
echo "# Generate secret first:"
echo "openssl rand -base64 32"
echo ""
echo "# Add to Vercel:"
echo "vercel env add DATABASE_URL production"
echo "# → Paste Neon connection string"
echo ""
echo "vercel env add NEXTAUTH_SECRET production"
echo "# → Paste generated secret from above"
echo ""
echo "vercel env add NEXTAUTH_URL production"
echo "# → Paste your Vercel URL (https://booktarr-xxx.vercel.app)"
echo ""

echo "STEP 5: Redeploy with Variables"
echo "--------------------------------"
echo "vercel --prod"
echo ""

echo "STEP 6: Run Database Migrations"
echo "-------------------------------"
echo "vercel env pull .env.local"
echo "npm run db:migrate"
echo ""

echo "STEP 7: Test Deployment"
echo "-----------------------"
echo "# Replace YOUR_URL with your actual Vercel URL"
echo "curl https://YOUR_URL.vercel.app/api/health"
echo ""
echo "./scripts/test-staging.sh https://YOUR_URL.vercel.app"
echo ""

echo "========================================="
echo "DONE! 🎉"
echo "========================================="
