"""add_metadata_enhancement_fields

Revision ID: 5143eeb76390
Revises: 
Create Date: 2025-07-10 01:52:08.341298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5143eeb76390'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('metadata_enhanced', sa.Boolean(), nullable=True))
    op.add_column('books', sa.Column('metadata_enhanced_date', sa.DateTime(), nullable=True))
    op.add_column('books', sa.Column('metadata_sources_used', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'metadata_sources_used')
    op.drop_column('books', 'metadata_enhanced_date')
    op.drop_column('books', 'metadata_enhanced')
    # ### end Alembic commands ###