"""add_reading_progress_fields

Revision ID: 7d92a1b34567
Revises: 5143eeb76390
Create Date: 2025-07-10 14:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d92a1b34567'
down_revision = '5143eeb76390'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('reading_status', sa.String(), nullable=True))
    op.add_column('books', sa.Column('reading_progress_pages', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('reading_progress_percentage', sa.Float(), nullable=True))
    op.add_column('books', sa.Column('date_started', sa.String(), nullable=True))
    op.add_column('books', sa.Column('date_finished', sa.String(), nullable=True))
    op.add_column('books', sa.Column('personal_rating', sa.Float(), nullable=True))
    op.add_column('books', sa.Column('personal_notes', sa.Text(), nullable=True))
    op.add_column('books', sa.Column('reading_goal_id', sa.String(), nullable=True))
    op.add_column('books', sa.Column('times_read', sa.Integer(), nullable=True))
    
    # Set default values for existing records
    op.execute("UPDATE books SET reading_status = 'unread' WHERE reading_status IS NULL")
    op.execute("UPDATE books SET times_read = 0 WHERE times_read IS NULL")
    
    # Make reading_status and times_read non-nullable with defaults
    op.alter_column('books', 'reading_status', nullable=False, server_default='unread')
    op.alter_column('books', 'times_read', nullable=False, server_default='0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'times_read')
    op.drop_column('books', 'reading_goal_id')
    op.drop_column('books', 'personal_notes')
    op.drop_column('books', 'personal_rating')
    op.drop_column('books', 'date_finished')
    op.drop_column('books', 'date_started')
    op.drop_column('books', 'reading_progress_percentage')
    op.drop_column('books', 'reading_progress_pages')
    op.drop_column('books', 'reading_status')
    # ### end Alembic commands ###